name: CI/CD

on:
  push:
    branches:
      - main # Change this to your main branch
    paths:
      - app/**
      - requirements.txt
      - zappa_settings.json
      - application.py
      - migrations/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        cache: "pip"

    - name: Set up the virtual environment and install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to AWS with Zappa
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        source env/bin/activate
        # Change "production" to your Zappa environment
        zappa update production 
